databases:
  - name: django-marketplace-db
    databaseName: django_marketplace
    user: django_marketplace

services:
  - type: web
    name: django-marketplace
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn marketplace.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-marketplace-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4